### ISSUE TITLE
time.clock has been removed in Python 3.8

### ISSUE THREAD

**Issue by npucino** [pyReef-model/RADWave#3]
By running the **processAltimeterData** function, the following AttributeError appear:

AttributeError                            Traceback (most recent call last)
<ipython-input-12-0a0786b1e479> in <module>
----> 1 vic.processAltimeterData(altimeter_pick='all', saveCSV = 'altimeterData.csv')

~\AppData\Local\Continuum\anaconda3\envs\wave_analysis\lib\site-packages\RADWave\altiwave.py in processAltimeterData(self, altimeter_pick, saveCSV)
    282         print("Processing Altimeter Dataset \n")
    283 
--> 284         **t0 = time.clock()**
    285         p = 0
    286         combineframe = None

**AttributeError: module 'time' has no attribute 'clock'**

I am working in with Python 3.8.2.
The issue is the fact that in 3.8 there is no time.clock anymore.

Easy fix could be replace the time.clock() with time.time()?
Cheers
Nick

**Comment by tristan-salles** [comment]
Thanks for pointing this! I have updated the code accordingly.

**Comment by tristan-salles** [comment]
A new pypi package v.1.0.1 has been uploaded...
